# Generated by Django 4.1 on 2022-08-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('codigo', models.IntegerField()),
                ('preciocompra', models.TextField()),
                ('precioventa', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('estado', models.TextField()),
            ],
        ),
    ]
